package com.sgifdbackend.demo.enums;

public enum ModuleName {
    PARAMETRAGE,
    ACCORD_COOPERATION,
    COOPERATION_DECENTRALISEE,
    REQUETE_FINANCEMENT,
    SUIVI_PROJET,
    AIDE_ALIMENTAIRE_BOURSE_ET_SECOURS,
    INVESTISSEMENT_DIRECT_ETRANGER,
    PARTENARIAT_PUBLIC_PRIVE,
    FOND_SPECIFIQUE,
    COMMISSION_MIXTE_DOCUMENT_STRAGTEGIE_PAYS,
    UTILISATEUR_SYSTEME,
    OUTPUT_RAPPORT
}
